name: github pages

on:
  push:
    branches:
      - master

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: select python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.9.21'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx
        python -m pip install sphinx_rtd_theme

    - name: build documentation
      run: |
        cd docs
        make html
        touch _build/html/.nojekyll

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: docs/_build/html
